'''

1. Write a Python program to find the single number which occurs odd numbers and other numbers occur even number.

2. Write a Python program to compute the sum of all the multiples of 3 or 5 below 500.
All the natural numbers below 12 that are multiples of 3 or 5, we get 3, 5, 6, 9 and 10. The sum of these multiples is 33.

3. Write a Python program to compute the sum of the even-valued terms in the Fibonacci sequence whose values do not exceed one million.
Note: Fibonacci series is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

'''
